name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          CNAME: svatebni.mazli.ci
          GITHUB_ACTOR: TomasTomecek
          HUGO_VERSION: 0.93.3
          HUGO_EXTENDED: true
          TARGET_BRANCH: www
          TOKEN: ${{ secrets.TOKEN }}
